name: 'pr-publishing'
description: 'An action for publishing PRs'

inputs:
  endpoint:
    description: Endpoint to login
  endpoint-input:
    description: If endpoint is not provided, it will be gotten from the input value with this name of the action
    default: endpoint

runs:
  using: node20
  main: dist/index.js
